### ISSUE TITLE
Voucher shown in report.verify_consistency

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#287]
DB: Lodo/2016-09-23-cant_open_bank.sql.zip

Click on report for possible mistakes:
![bilagsfeil](https://cloud.githubusercontent.com/assets/11351084/19628178/282d5bc0-9958-11e6-8cfe-d9c188cefa1f.png)

The to first ones: first B52404, find voucher in diary(DAGBOK) 
![diary](https://cloud.githubusercontent.com/assets/11351084/19628203/a9ceafe4-9958-11e6-940b-4cde61a0a311.png)

The last voucher line(426081) is not visible, but is wrong.Should not be there. 
The second voucher(B52467) has voucher line(465527) which should not be there.

**Comment by mladjo2505** [comment]
The issue with those bank journals is that they have vouchers with a supplier account, and that supplier has a foreign currency set.
Each supplier voucher has another hidden voucher for the main account all suppliers (2400) (That is how it should be) but when we change from that account to another which is not a supplier the hidden voucher should become inactive, and when currency is enabled on a supplier account that we are changing from, it doesn't.
Have to research more how currency enabled affects the voucher update action.
Would like to discuss more about this issue with @sls-lnluksa after finding another solution to this since i have an 'ugly' patch for it so far.

**Comment by Baxxx** [comment]
The second voucher problem was fixed as a side effect from currency rework.

How to reproduce error from first voucher:
1. Create a bank journal, set in value to 1000.
2. Counter line appears, change it to any *customer*
3. Change the last line's value to 700. After save, we have three lines: +1000, -300, -700
4. Change the line's value from 700 to 450. After save, we have four lines: +1000, -550, -300, -450. (❓ )
5. Change the line value from 300 to 550, and save.

After this, we have 3 lines: +1000, -550, -450.
In DB, we have 3 hidden lines (instead of two): -450, -550, -550. It appears like the first hidden line was made from the -550 voucher line, and the second was made from that hidden line.

If we change the 550 line from customer to something else (result account), only one hidden line will become inactive (the one that was made from voucher)
