### ISSUE TITLE
Line total without tax and tax is different on FB and LODO

### ISSUE THREAD

**Issue by sls-lnluksa** [dodoas/lodo#366]
The invoice which came through XML to FB was downloaded to LODO, and it had different line total without tax and line total tax.

This is the example:
https://fakturabank.no/invoices/204616
Ocean Cafe Bar AS U6934

Data sent to LODO should be same as the one which we received with XML in FB.

**Comment by Baxxx** [comment]
Fakturabank invoice.id = `204616`, invoice.invoiceno = `831887699`
Tax: `25%`

|   -*Line 1*-  | Unit price | Quantity | Price w/o tax | Tax |
| --- | --- | --- | --- | --- |
| XML | 49.33 | 1104 | 54462.64 | 13615.66 |
| FB show | 49.33 | 1104.00 | 54462.64 | 13615.66 |
| FB XML export | 49.33 | 1104.0 | 54462.64 | 13615.66 |
| Lodo receives | 49.33 | 1104.0 | 54462.64 | 13615.66 |
| Lodo saves | 49.3300 | 1104.0000 | / | 13615.66 |
| Lodo show | 49.33 | 1104.0 | 54460.32 | 13615.08 |

|   -*Line 2*-  | Unit price | Quantity | Price w/o tax | Tax |
| --- | --- | --- | --- | --- |
| XML | 49.33 | -151 | -7449.15 | -1862.29 |
| FB show | 49.33 | -151 | -7449.15 | -1862.29 |
| FB XML export | 49.33 | -151 | -7449.15 | -1862.29 |
| Lodo receives | 49.33 | -151 | -7449.15 | -1862.29 |
| Lodo saves | 49.3300 | -151.0000 | / | -1862.29 |
| Lodo show | 49.33 | -151.00 | -7448.83 | -1862.21 |

|   -*Totals*-  | Total w/o tax | Tax | Total w/ tax |
| --- | --- | --- | --- |
| XML | 47013.49 | 11753.37 | 58766.86 |
| FB show | 47013.49 | 11753.37 | 58766.86 |
| FB XML export | 47013.49 | 11753.37 | 58766.86 |
| Lodo receives | 47013.49 | 11753.37 | 58766.86 |
| Lodo saves | / | / | 58766.86 |
| Lodo show | 47011.49 | 11752.87 | 58764.36 |

Research conclusion: Origin XML had rounded values which were not correct (example: `49.33 * 1104 = 54460.32`, instead of `54462.64` which was provided). The XML does not contain any trace of rounding amounts. I suspect it is the price that was rounded from `49.3321` to `49.33`. Fakturabank saves this value anyway, and displays it, without calculating, and exports the same way. When Lodo is receiving, it only takes the invoice lines price and quantity, and calculates everything in the views.

**Comment by Baxxx** [comment]
Also, the xml exported from Fakturabank is not valid by EHF. Besides the miscalculations, it's missing values from some of mandatory fields (example: `LegalMonetaryTotal->LineExtensionAmount`, `LegalMonetaryTotal->TaxInclusiveAmount`). It is probably because of the outdated e2b_invoice_reader. (new issue)

**Comment by sls-lnluksa** [comment]
After consulting with Arnt Telhaug:
We should investigate how it is possible to change logic in lodo so we actually use values received by XML.
The most important amount for accounting is `total with tax`.

Quantity * unit_price don't need to be 100% correct. So I assume LODO should save Price w/o tax for lines and use that field for display it on lines, also for calculating Total w/o tax. (Reinvestigate should we save Total w/o tax directly from XML)
