### ISSUE TITLE
Lodo on 16.04

### ISSUE THREAD

**Issue by MrdjanStojimirovic** [dodoas/lodo#419]
Try to make login.lodo.no and lodo.no work on ubuntu 16.04

- [ ] Investigate can we install PHP 5.3.3-7. If i remember correctly this was one of main issues. 
- [ ] @stoivo is working on lodo.no which is an old rails application. That should have no troubles running on 16.04. Still try to set it up on 16.04

**Comment by mladjo2505** [comment]
Installation:
- It is possible to install MySQL server version 5.1.73 from source using the modified version of [this](https://gist.github.com/shichao-an/f5639ecd551496ac2d70) script
- Installation of php of the required version cannot be installed from source due to some failing dependencies. The old versions of php are not maintained anymore even from the custom ppa repositories. The closest version to the required one is 5.6 which causes a lot of trouble with the mysqli implementation and so takes a lot of time to fix.
- Apache version causes some trouble but all of it is fixable
- After all the tinkering I still could not get the app to run(not even get to the login screen)

Proposal 1:
Leave on 12.04 as it is now.

Proposal 2:
Clean up and upgrade the app so it can run on 16.04 or newer (slow and painstaking)

Proposal 3:
Reimplement the app using a newer technology that can run on 16.04 or newer (faster than proposal 2)

**Comment by sls-lnluksa** [comment]
We decided proposal 1 for now
