### ISSUE TITLE
Some outgoing invoices are saving each voucher line multiple times instead of once

### ISSUE THREAD

**Issue by hildegunn95** [dodoas/lodo#59]
For some clients some outgoing invoices are saving some of the voucher lines multiple times.
When saving the invoice again(from invoice.edit page), additional correct lines are added to the voucher from the invoice.

It should only save each invoice line once and its VAT lines.

"Linjekontroll" is showing in outgoing invoices list page for these invoices, and it should. 

Invoice date and due date are not saved correctly, when you look at the invoice and the voucher, these dates do not match. 

DB: Uni Aryal

Edit: 
- [x] Fix issue
- [x] Display error with "Linjekontroll"

**Comment by agvald** [comment]
18 hours used on Display error with "Linjekontroll", 18 hours estimated for Fix issue at least

**Comment by hildegunn95** [comment]
db dump: fb2014:2016-07-29-invoice_with_multiple_voucher_lines.sql.zip

**Comment by Baxxx** [comment]
To reproduce the problem:

1. Go to outgoing invoices.
2. Type in date, period, click create new invoice.
3. When the invoice.edit opened, click on the invoice number, journal page should open.
4. Click new voucher line `Ny postering til bilag`
5. Go back to the invoice.edit page, and populate the fields, fill the invoice with correct data.
6. When you save the invoice, this will be bookkept. If you try to save again, these lines are *added again* to the journal.

This occurs because when we create a new line on an empty journal, it has all the fields empty (including the VoucherDate and VoucherPeriod). When you save the invoice it should delete the entire journal by fetching its head, and if that vouchers period is open, it will allow deletion. Since it was empty for this voucher, which is head because it was created before the others, this will not delete the journal and start from scratch but keep adding lines instead.
